#include "../../src/candidate/CandidateSkin.h"
#include <cassert>
#include <cmath>
#include <string>
#include <string_view>

using msime::mac::NativeCandidateTokens;
using msime::mac::Rgba;
using msime::mac::ToolbarSkinTokens;
static void CheckColor(Rgba value, unsigned rgb, float alpha = 1) {
    assert(std::abs(value.r - ((rgb >> 16) & 255) / 255.f) < 0.00001f);
    assert(std::abs(value.g - ((rgb >> 8) & 255) / 255.f) < 0.00001f);
    assert(std::abs(value.b - (rgb & 255) / 255.f) < 0.00001f);
    assert(std::abs(value.a - alpha) < 0.00001f);
}
static bool SameColor(Rgba left, Rgba right) {
    return std::abs(left.r - right.r) < 0.00001f && std::abs(left.g - right.g) < 0.00001f &&
           std::abs(left.b - right.b) < 0.00001f && std::abs(left.a - right.a) < 0.00001f;
}
static bool SameTokens(const msime::mac::SkinTokens &left, const msime::mac::SkinTokens &right) {
    return SameColor(left.surface, right.surface) && SameColor(left.border, right.border) &&
           SameColor(left.text, right.text) && SameColor(left.number, right.number) &&
           SameColor(left.selected, right.selected) && SameColor(left.selectedText, right.selectedText) &&
           SameColor(left.selectedNumber, right.selectedNumber) && SameColor(left.hover, right.hover) &&
           SameColor(left.accent, right.accent) && left.radius == right.radius &&
           left.showSelectedBar == right.showSelectedBar;
}
int main() {
    msime::mac::SetDefaultSkinsRoot("/synthetic/movable-state/skins");
    assert(msime::mac::DefaultSkinsRoot() == "/synthetic/movable-state/skins");
    msime::mac::SetDefaultSkinsRoot({});

    // Golden values from design-tokens-desktop §1.2 (the macOS column), not generated by the resolver: a translucent system card, the brand green as a solid selection with white text, 10pt card and 6pt rows.
    struct Fixture { bool dark; unsigned surface, border, text, number, accent, hover; float borderAlpha, hoverAlpha; };
    const Fixture fixtures[] = {
        {false, 0xFFFFFF, 0x000000, 0x1D1D1F, 0x6E6E73, 0x2C7A4B, 0x000000, .12f, .06f},
        {true, 0x28282A, 0xFFFFFF, 0xF5F5F7, 0x98989D, 0x5FBF84, 0xFFFFFF, .12f, .10f},
    };
    for (const auto &f : fixtures) {
        const auto t = NativeCandidateTokens(f.dark);
        CheckColor(t.surface, f.surface, .97f);
        CheckColor(t.border, f.border, f.borderAlpha);
        CheckColor(t.text, f.text);
        CheckColor(t.number, f.number);
        CheckColor(t.accent, f.accent);
        CheckColor(t.hover, f.hover, f.hoverAlpha);
        CheckColor(t.selected, f.accent);
        CheckColor(t.selectedHover, f.accent);
        CheckColor(t.selectedText, 0xFFFFFF);
        CheckColor(t.selectedNumber, 0xFFFFFF, .82f);
        assert(t.radius == 10 && t.candidateRadius == 6 && t.selectedRadius == 6 && t.borderWidth == 1 && t.pad == 6 &&
               !t.showSelectedBar);
        // Selected and hover rows share one 6pt shape; only an end row of a highlighted run takes the card radius.
        assert(msime::mac::CandidateRowRadius(t, true) == 6);
        assert(msime::mac::CandidateRowRadius(t, true, true, false) == t.radius);
        assert(msime::mac::CandidateRowRadius(t, true, false, true) == t.radius);
        assert(msime::mac::CandidateRowRadius(t, false) == 6);
    }
    msime::mac::SkinTokens split;
    split.candidateRadius = 3.0f;
    split.selectedRadius = 7.0f;
    assert(msime::mac::CandidateRowRadius(split, true) == 7.0f);
    assert(msime::mac::CandidateRowRadius(split, true, true, false) == split.radius);
    assert(msime::mac::CandidateRowRadius(split, false) == 3.0f);

    // The user's 候选窗 style over a resolved skin. The defaults change nothing at all.
    {
        msime::mac::ResolvedSkin skin;
        skin.tokens = NativeCandidateTokens(false);
        skin.backgroundOpacity = 0.8;
        skin.decorationTopDip = 40.0;
        skin.decorationWidthDip = 60.0;
        skin.minWidthDip = 200.0;
        const auto untouched = msime::mac::StyledCandidateSkin(skin, {});
        assert(SameTokens(untouched.tokens, skin.tokens) && untouched.tokens.candidateRadius == 6 && untouched.tokens.pad == 6);
        assert(untouched.backgroundOpacity == 0.8 && untouched.decorationTopDip == 40.0 && untouched.minWidthDip == 200.0);

        // A user radius beats the package's (already in tokens.radius) and pulls the rows in with it; a larger one leaves the rows at their own 6pt.
        auto packaged = skin;
        packaged.tokens.radius = 20.0f;
        msime::mac::CandidateWindowStyle style;
        style.cornerRadius = 3.0;
        const auto tight = msime::mac::StyledCandidateSkin(packaged, style);
        assert(tight.tokens.radius == 3.0f && tight.tokens.candidateRadius == 3.0f && tight.tokens.selectedRadius == 3.0f);
        style.cornerRadius = 0.0;
        assert(msime::mac::StyledCandidateSkin(packaged, style).tokens.radius == 0.0f);
        style.cornerRadius = 14.0;
        const auto loose = msime::mac::StyledCandidateSkin(packaged, style);
        assert(loose.tokens.radius == 14.0f && loose.tokens.candidateRadius == 6.0f && loose.tokens.selectedRadius == 6.0f);
        // Without a user radius the package's stays, and the rows keep the host's 6pt shape they drew before the setting existed.
        auto square = skin;
        square.tokens.radius = 2.0f;
        const auto packageOnly = msime::mac::StyledCandidateSkin(square, {});
        assert(packageOnly.tokens.radius == 2.0f && packageOnly.tokens.candidateRadius == 6.0f && packageOnly.tokens.selectedRadius == 6.0f);

        // Opacity fades the card, its border and the package background, never the text, numbers or selection.
        msime::mac::CandidateWindowStyle faded;
        faded.opacity = 0.5;
        const auto half = msime::mac::StyledCandidateSkin(skin, faded);
        assert(std::abs(half.tokens.surface.a - skin.tokens.surface.a * 0.5f) < 0.00001f);
        assert(std::abs(half.tokens.border.a - skin.tokens.border.a * 0.5f) < 0.00001f);
        assert(std::abs(half.backgroundOpacity - 0.4) < 0.00001);
        assert(SameColor(half.tokens.text, skin.tokens.text) && SameColor(half.tokens.number, skin.tokens.number));
        assert(SameColor(half.tokens.selected, skin.tokens.selected) && SameColor(half.tokens.selectedText, skin.tokens.selectedText));
        assert(SameColor(half.tokens.accent, skin.tokens.accent) && SameColor(half.tokens.hover, skin.tokens.hover));

        // The scale multiplies every length the skin carries, after the radius is chosen, and leaves the hairline alone.
        msime::mac::CandidateWindowStyle large;
        large.scale = 1.5;
        large.cornerRadius = 8.0;
        const auto scaled = msime::mac::StyledCandidateSkin(skin, large);
        assert(scaled.tokens.radius == 12.0f && scaled.tokens.candidateRadius == 9.0f && scaled.tokens.selectedRadius == 9.0f);
        assert(scaled.tokens.pad == 9.0f && scaled.tokens.borderWidth == skin.tokens.borderWidth);
        assert(scaled.decorationTopDip == 60.0 && scaled.decorationWidthDip == 90.0 && scaled.minWidthDip == 300.0);
        assert(SameColor(scaled.tokens.surface, skin.tokens.surface) && scaled.backgroundOpacity == 0.8);
    }

    // The picker is the shared catalog, in its order, and only its ids are themes.
    const auto &catalog = msime::mac::ThemeCatalog();
    const char *ids[] = {"system", "shuishan", "light", "paper", "night", "ink", "custom"};
    assert(catalog.size() == 7);
    for (size_t index = 0; index < catalog.size(); ++index) {
        assert(catalog[index].id == ids[index] && !catalog[index].title.empty());
        assert(msime::mac::IsGlobalThemeId(ids[index]));
        assert(msime::mac::IsThemeBaseId(ids[index]) == (index + 1 < catalog.size()));
    }
    assert(catalog[0].appearance.empty() && !catalog[0].hasPreview && catalog.back().appearance.empty());
    assert(catalog[1].appearance == "dark" && catalog[1].hasPreview && catalog[2].appearance == "light");
    CheckColor(catalog[1].previewAccent, 0x7FE08E);
    for (const char *retired : {"fluent", "wechat", "graphite", "willow_green", "Custom", ""})
        assert(!msime::mac::IsGlobalThemeId(retired));
    assert(msime::mac::ThemeTitle("shuishan") == "水杉" && msime::mac::ThemeTitle("custom") == "自定义");

    const msime::mac::CustomTheme none;
    for (bool dark : {false, true}) {
        // `system` resolves every slot to the native token in the system's mode and fixes no mode.
        const auto system = msime::mac::ResolveSkin("system", none, dark, "horizontal", {});
        assert(system.id == "system" && !system.fixedDark && system.dark == dark && system.candidateSkin.empty());
        assert(SameTokens(system.tokens, NativeCandidateTokens(dark)));
        // An unknown id draws `system` meanwhile.
        const auto unknown = msime::mac::ResolveSkin("fluent", none, dark, "horizontal", {});
        assert(unknown.id == "system" && SameTokens(unknown.tokens, NativeCandidateTokens(dark)));
        // A built-in theme fixes its mode whatever the system's is, and paints the shared palette.
        const auto shuishan = msime::mac::ResolveSkin("shuishan", none, dark, "horizontal", {});
        assert(shuishan.id == "shuishan" && shuishan.fixedDark == true && shuishan.dark);
        CheckColor(shuishan.tokens.surface, 0x2A2B27);
        CheckColor(shuishan.tokens.text, 0xFFFFFF);
        CheckColor(shuishan.tokens.accent, 0x7FE08E);
        CheckColor(shuishan.tokens.selected, 0x7FE08E, 0x24 / 255.f);
        CheckColor(shuishan.tokens.selectedText, 0x7FE08E);
        assert(SameColor(shuishan.tokens.selectedHover, shuishan.tokens.selected));
        const auto paper = msime::mac::ResolveSkin("paper", none, dark, "vertical", {});
        assert(paper.fixedDark == false && !paper.dark);
        CheckColor(paper.tokens.surface, 0xF7F5F0);
        // The native geometry stays: themes only recolour.
        assert(paper.tokens.radius == 10 && paper.tokens.selectedRadius == 6 && !paper.tokens.showSelectedBar);

        // `custom` with no base follows the system mode; an explicit text picker also sets the numbers.
        msime::mac::CustomTheme picked;
        picked.candidateColors.text = "#123456";
        picked.candidateColors.accent = "#ABCDEF";
        const auto custom = msime::mac::ResolveSkin("custom", picked, dark, "horizontal", {});
        assert(custom.id == "custom" && !custom.fixedDark && custom.dark == dark);
        CheckColor(custom.tokens.text, 0x123456);
        CheckColor(custom.tokens.accent, 0xABCDEF);
        CheckColor(custom.tokens.number, 0x123456, 0x9D / 255.f);
        // A null `selected` is the native solid fill, so it follows the picked accent; its foregrounds follow that fill, which is light here, so they turn dark rather than staying the native white.
        CheckColor(custom.tokens.selected, 0xABCDEF);
        assert(SameColor(custom.tokens.selectedText, Rgba{0.1f, 0.1f, 0.1f, 1.0f}));
        assert(SameColor(custom.tokens.selectedNumber, Rgba{0.1f, 0.1f, 0.1f, 0.82f}));
        // A dark picked accent keeps the native white. A picked selection colour has its foregrounds chosen by the shared core instead, black or white by its luminance (custom-theme-parity.json), so a light one reads in black.
        msime::mac::CustomTheme darkAccent;
        darkAccent.candidateColors.accent = "#1F4E3D";
        const auto darkFill = msime::mac::ResolveSkin("custom", darkAccent, dark, "horizontal", {});
        CheckColor(darkFill.tokens.selectedText, 0xFFFFFF);
        CheckColor(darkFill.tokens.selectedNumber, 0xFFFFFF, .82f);
        msime::mac::CustomTheme lightFill;
        lightFill.candidateColors.selected = "#E8E8E8";
        const auto light = msime::mac::ResolveSkin("custom", lightFill, dark, "horizontal", {});
        CheckColor(light.tokens.selected, 0xE8E8E8);
        CheckColor(light.tokens.selectedText, 0x000000);
        CheckColor(light.tokens.selectedNumber, 0x000000, 0x9D / 255.f);
        // A custom theme over a built-in one takes that theme's mode and fills the unpicked slots from it.
        picked.base = "night";
        const auto overNight = msime::mac::ResolveSkin("custom", picked, dark, "horizontal", {});
        assert(overNight.fixedDark == true && overNight.dark);
        CheckColor(overNight.tokens.surface, 0x16262F);
        CheckColor(overNight.tokens.text, 0x123456);
        // The custom pickers mean nothing while another theme is selected.
        const auto ink = msime::mac::ResolveSkin("ink", picked, dark, "horizontal", {});
        CheckColor(ink.tokens.text, 0x9A9A9A);
        // A malformed picker value is dropped rather than failing the whole request.
        msime::mac::CustomTheme malformed;
        malformed.candidateColors.text = "red";
        malformed.candidateSkin = "../escape";
        const auto dropped = msime::mac::ResolveSkin("custom", malformed, dark, "horizontal", {});
        assert(dropped.id == "custom" && dropped.candidateSkin.empty());
        assert(SameColor(dropped.tokens.text, NativeCandidateTokens(dark).text));

        // Without a package the toolbar is the candidate palette itself.
        assert(SameTokens(ToolbarSkinTokens(system, {}), system.tokens));
        assert(SameTokens(ToolbarSkinTokens(shuishan, {}), shuishan.tokens));
        assert(SameTokens(ToolbarSkinTokens(overNight, {}), overNight.tokens));
        // Without a package no theme has a translation colour of its own (secondary follows number) and the toolbar has no divider colour of its own.
        for (const auto *resolved : {&system, &shuishan, &paper, &custom, &overNight, &ink})
        {
            assert(!resolved->tokens.translation && !ToolbarSkinTokens(*resolved, {}).divider);
            assert(resolved->backgroundPath.empty() && resolved->decorationAlign == msime::mac::DecorationAlign::right);
        }
        // A card radius, however it got there, never reaches the toolbar.
        auto rounded = system;
        rounded.tokens.radius = 24.0f;
        assert(ToolbarSkinTokens(rounded, {}).radius == NativeCandidateTokens(rounded.dark).radius);
    }
}
